export interface User {

    /** Primary key */
    id: number;

    /** Max length: 35, non-nullable */
    firstName: string;

    /** Max length: 35, non-nullable */
    lastName: string;

    /** Max length: 254, non-nullable */
    email: string;

    /** Not important. Nullable. Generated by concatenation in backend */
    fullName: string;

}
