import { UserPassword } from './user-password.model';


export interface User {

    /** Primary key */
    id: number;

    /** Max length: 20, non-nullable */
    login: string;

    /** Non-nullable */
    passwordId: number;

    /** Non-nullable, never included */
    userPassword: UserPassword;

    /** Max length: 35, non-nullable */
    firstName: string;

    /** Max length: 35, non-nullable */
    lastName: string;

    /** Max length: 254, non-nullable */
    email: string;

    /** Not important. Nullable. Generated by concatenation in backend */
    fullName: string;

}
